package com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2014-09-22T09:13:16.236+10:00
 * Generated source version: 2.4.9
 * 
 */
@WebService(targetNamespace = "http://webservice.com/", name = "TestWS")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWS {

    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.com/", className = "com.webservice.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.HelloResponse")
    public void hello();
}
